gallery/urls.py
from django.conf.urls import url
from . import views

#url patterns
urlpatterns = [
    url(r'^$', views.picture_list,name='picture_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.picture_list,name='picture_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.picture_detail,name='picture_detail'),
]

mygallery/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# aded patterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('gallery.urls',namespace='gallery') ),
]
#settings debug
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT )

gallery/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
#category model
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('gallery:picture_list_by_category',
                           args=[self.slug])

#picture model
class Picture(models.Model):
    category = models.ForeignKey(Category,related_name='pictures')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='pictures/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=200,default=True)
    url = models.CharField(max_length=200,default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
      


    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('gallery:picture_detail',args=[self.id, self.slug])
        

gallery/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category, Picture

# Create your views here.
def picture_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    pictures = Picture.objects.filter()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        pictures = pictures.filter(category=category)
    return render(request, 'gallery/picture/list.html',{'category': category,
                   'categories': categories,
                   'pictures': pictures})


def picture_detail(request, id, slug):
    picture = get_object_or_404(Picture,id=id,slug=slug)
    return render(request,'gallery/picture/detail.html',{'picture': picture})

# def search_results(request):
#     if 'picture' in request.GET and request.GET['picture']:
#         search_input = request.GET.get('image')
#         searched_images = Image.search_by_category(search_input)
#         message = f"{search_input}"

#         return render(request, 'search.html', {"message":message, "images":searched_images})

#     else:
#         message = "Please input something in the search field"
#         return render(request, 'search.html', {'message':message})

gallery/templates/gallery/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}My Gallery{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
  <div id="header">
    <a href="/" class="logo">My Gallery</a>
    <form class="form-inline search" role="search" action="">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search" name='image'>
      <button class="btn" type="submit">Search</button>
  </form>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

gallery/templates/gallery/picture/detail.html
{% extends "gallery/base.html" %}
{% load static %}

{% block title %}
  {{ picture.name }}
{% endblock %}

{% block content %}
  <div class="picture-detail">
    <img src="{% if picture.image %}{{ picture.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" >
    <h1>{{ picture.name }}</h1>
    <h2><a href="{{ picture.category.get_absolute_url }}">{{ picture.category }}</a></h2>
    <p class="location">Location: {{ picture.location }}</p>
    {{ picture.description|linebreaks }}
    <input type="text" value="{{ picture.url }}" id="myInput">
    <button onclick="myFunction()">Copy url</button>
    <script>
    function myFunction() {
      var copyText = document.getElementById("myInput");
      copyText.select();
      copyText.setSelectionRange(0, 99999)
      document.execCommand("copy");
      alert("Copied the text: " + copyText.value);
    }
    </script>
    
  </div>
{% endblock %}

gallery/templates/gallery/picture/list.html
{% extends "gallery/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Pictures{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "gallery:picture_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="picture-list">
    <h1>{% if category %}{{ category.name }}{% else %}Pictures{% endif %}</h1>
    {% for picture in pictures %}
      <div class="item">
        <a href="{{ picture.get_absolute_url }}">
          <img src="{% if picture.image %}{{ picture.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ picture.get_absolute_url }}">{{ picture.name }}</a><br>
        {{ picture.location }}
      </div>
    {% endfor %}
  </div>
{% endblock %}

gallery/templates/gallery/picture/search.html
{% extends "gallery/base.html" %}{% block content %}
{% load static %}
<div class="row">
    {% for picture in pictures %} {% if pictures %}
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 columns">
        <div class="scale">
            <div class="opacity">
                <div class="view">
                    <a href="" class="btn-view">View Image</a>
                </div>
            </div>
            <img src="{{picture.url}}" alt="Image" class="img-fluid">
        </div>
    </div>
    {% endif %} {% endfor %}
</div>
{% endblock %}